-- Run this key in the Supabase SQL Editor

create table tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  priority text check (priority in ('high', 'medium', 'low')) default 'medium',
  is_complete boolean default false,
  created_at timestamptz default now()
);
